# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

INCLUDES += -Ilib/bx/include -Ilib/bimg/include -Ilib/bgfx/include -Ilib/bgfx/3rdparty -Ilib/bgfx/3rdparty/dxsdk/include -Ilib/bgfx/3rdparty/khronos
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_x64)
RESCOMP = windres
TARGETDIR = bin/Debug-linux-x86_64/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Debug-linux-x86_64/BGFX
DEFINES += -DDEBUG -D__STDC_FORMAT_MACROS -DBGFX_CONFIG_DEBUG=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),debug_xbox)
RESCOMP = windres
TARGETDIR = bin/Debug-linux-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Debug-linux-/BGFX/Xbox
DEFINES += -DDEBUG -D__STDC_FORMAT_MACROS -DBGFX_CONFIG_DEBUG=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),debug_playstation)
RESCOMP = windres
TARGETDIR = bin/Debug-linux-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Debug-linux-/BGFX/PlayStation
DEFINES += -DDEBUG -D__STDC_FORMAT_MACROS -DBGFX_CONFIG_DEBUG=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),debug_macos)
RESCOMP = windres
TARGETDIR = bin/Debug-linux-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Debug-linux-/BGFX/macOS
DEFINES += -DDEBUG -D__STDC_FORMAT_MACROS -DBGFX_CONFIG_DEBUG=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),debug_ios)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = bin/Debug-ios-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Debug-ios-/BGFX
DEFINES += -DDEBUG -D__STDC_FORMAT_MACROS -DBGFX_CONFIG_DEBUG=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),debug_linux_x64)
RESCOMP = windres
TARGETDIR = bin/Debug-linux-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Debug-linux-/BGFX/Linux_x64
DEFINES += -DDEBUG -D__STDC_FORMAT_MACROS -DBGFX_CONFIG_DEBUG=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),release_x64)
RESCOMP = windres
TARGETDIR = bin/Release-linux-x86_64/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Release-linux-x86_64/BGFX
DEFINES += -DNDEBUG -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),release_xbox)
RESCOMP = windres
TARGETDIR = bin/Release-linux-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Release-linux-/BGFX/Xbox
DEFINES += -DNDEBUG -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2
ALL_LDFLAGS += $(LDFLAGS) -s

else ifeq ($(config),release_playstation)
RESCOMP = windres
TARGETDIR = bin/Release-linux-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Release-linux-/BGFX/PlayStation
DEFINES += -DNDEBUG -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2
ALL_LDFLAGS += $(LDFLAGS) -s

else ifeq ($(config),release_macos)
RESCOMP = windres
TARGETDIR = bin/Release-linux-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Release-linux-/BGFX/macOS
DEFINES += -DNDEBUG -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2
ALL_LDFLAGS += $(LDFLAGS) -s

else ifeq ($(config),release_ios)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = bin/Release-ios-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Release-ios-/BGFX
DEFINES += -DNDEBUG -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),release_linux_x64)
RESCOMP = windres
TARGETDIR = bin/Release-linux-/BGFX
TARGET = $(TARGETDIR)/libBGFX.a
OBJDIR = bin-int/Release-linux-/BGFX/Linux_x64
DEFINES += -DNDEBUG -D__STDC_FORMAT_MACROS
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2
ALL_LDFLAGS += $(LDFLAGS) -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/bgfx.o
GENERATED += $(OBJDIR)/debug_renderdoc.o
GENERATED += $(OBJDIR)/dxgi.o
GENERATED += $(OBJDIR)/glcontext_egl.o
GENERATED += $(OBJDIR)/glcontext_glx.o
GENERATED += $(OBJDIR)/glcontext_html5.o
GENERATED += $(OBJDIR)/glcontext_wgl.o
GENERATED += $(OBJDIR)/nvapi.o
GENERATED += $(OBJDIR)/renderer_d3d11.o
GENERATED += $(OBJDIR)/renderer_d3d12.o
GENERATED += $(OBJDIR)/renderer_d3d9.o
GENERATED += $(OBJDIR)/renderer_gl.o
GENERATED += $(OBJDIR)/renderer_gnm.o
GENERATED += $(OBJDIR)/renderer_noop.o
GENERATED += $(OBJDIR)/renderer_nvn.o
GENERATED += $(OBJDIR)/renderer_vk.o
GENERATED += $(OBJDIR)/renderer_webgpu.o
GENERATED += $(OBJDIR)/shader.o
GENERATED += $(OBJDIR)/shader_dx9bc.o
GENERATED += $(OBJDIR)/shader_dxbc.o
GENERATED += $(OBJDIR)/shader_spirv.o
GENERATED += $(OBJDIR)/topology.o
GENERATED += $(OBJDIR)/vertexlayout.o
OBJECTS += $(OBJDIR)/bgfx.o
OBJECTS += $(OBJDIR)/debug_renderdoc.o
OBJECTS += $(OBJDIR)/dxgi.o
OBJECTS += $(OBJDIR)/glcontext_egl.o
OBJECTS += $(OBJDIR)/glcontext_glx.o
OBJECTS += $(OBJDIR)/glcontext_html5.o
OBJECTS += $(OBJDIR)/glcontext_wgl.o
OBJECTS += $(OBJDIR)/nvapi.o
OBJECTS += $(OBJDIR)/renderer_d3d11.o
OBJECTS += $(OBJDIR)/renderer_d3d12.o
OBJECTS += $(OBJDIR)/renderer_d3d9.o
OBJECTS += $(OBJDIR)/renderer_gl.o
OBJECTS += $(OBJDIR)/renderer_gnm.o
OBJECTS += $(OBJDIR)/renderer_noop.o
OBJECTS += $(OBJDIR)/renderer_nvn.o
OBJECTS += $(OBJDIR)/renderer_vk.o
OBJECTS += $(OBJDIR)/renderer_webgpu.o
OBJECTS += $(OBJDIR)/shader.o
OBJECTS += $(OBJDIR)/shader_dx9bc.o
OBJECTS += $(OBJDIR)/shader_dxbc.o
OBJECTS += $(OBJDIR)/shader_spirv.o
OBJECTS += $(OBJDIR)/topology.o
OBJECTS += $(OBJDIR)/vertexlayout.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking BGFX
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning BGFX
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/bgfx.o: lib/bgfx/src/bgfx.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/debug_renderdoc.o: lib/bgfx/src/debug_renderdoc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dxgi.o: lib/bgfx/src/dxgi.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/glcontext_egl.o: lib/bgfx/src/glcontext_egl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/glcontext_glx.o: lib/bgfx/src/glcontext_glx.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/glcontext_html5.o: lib/bgfx/src/glcontext_html5.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/glcontext_wgl.o: lib/bgfx/src/glcontext_wgl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/nvapi.o: lib/bgfx/src/nvapi.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer_d3d11.o: lib/bgfx/src/renderer_d3d11.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer_d3d12.o: lib/bgfx/src/renderer_d3d12.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer_d3d9.o: lib/bgfx/src/renderer_d3d9.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer_gl.o: lib/bgfx/src/renderer_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer_gnm.o: lib/bgfx/src/renderer_gnm.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer_noop.o: lib/bgfx/src/renderer_noop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer_nvn.o: lib/bgfx/src/renderer_nvn.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer_vk.o: lib/bgfx/src/renderer_vk.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/renderer_webgpu.o: lib/bgfx/src/renderer_webgpu.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shader.o: lib/bgfx/src/shader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shader_dx9bc.o: lib/bgfx/src/shader_dx9bc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shader_dxbc.o: lib/bgfx/src/shader_dxbc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shader_spirv.o: lib/bgfx/src/shader_spirv.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/topology.o: lib/bgfx/src/topology.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vertexlayout.o: lib/bgfx/src/vertexlayout.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif